# config
# cover: https://img.alicdn.com/tfs/TB1z2IKGNTpK1RjSZFKXXa2wXXa-2400-1600.jpg
cover: https://img.alicdn.com/tfs/TB1I_gYiggP7K4jSZFqXXamhVXa-4084-2728.jpg
# cover: https://img.alicdn.com/tfs/TB1gyk5hJTfau8jSZFwXXX1mVXa-2400-1603.jpg
# logo: https://img.alicdn.com/tfs/TB1M5l1BZfpK1RjSZFOXXa6nFXa-256-256.png
top_saying:
- title: <span class="site-title">MAY THE FORCE BE WITH YOU.</span>
# - content: You'll Never Walk Alone.
bottom_saying: 已阅，狗屁不通！

# Content
excerpt_link: Read More

# rss: /atom.xml

highlightjs: monokai_sublime

#Works
# works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml

#duoshuo name
# duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/ccforward
instagram: https://www.instagram.com/ccforward

cdn: https://cdn.jsdelivr.net/
cdnName: gh/ccforward/site@master/static/
cdnCombine: https://cdn.jsdelivr.net/

#about  timeline
# timeline:
# - num: 1
#   word: 2014/06/12-Start
# - num: 2
#   word: 2014/11/29-XXX
# - num: 3
#   word: 2015/02/18-DDD
# - num: 4
#   word: More

#Links
# links:
# - name: Kieran
#   link: http://go.kieran.top/
# - name: Name
#   link: http://domain.com/

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
